name : EC despliegue
on :
  push : 
    branches :
      - master
jobs :
  deploy :
    runs-on : ubuntu-latest

    steps:
      - name : 'checkout'
        uses :  actions/checkout@v4
      - name : 'installa node'
        uses : actions/setup-node@v4
        with:
          node-version : '14.0'
      - name: 'debug connection'
        run: |
          echo "Connecting to ${{ secrets.EC2_HOST }} as ${{ secrets.EC2_USER }}"
      - name : 'copy'
        uses : appleboy/scp-action@master
        with :
          host : ${{ secrets.EC_HOST }}
          username : ${{ secrets.EC2_USER }}
          key : ${{ secrets.EC2_SSH_KEY }}
          source : "app.js, package.json"
          target : "/home/ubuntu/app"
          verbose: true
      - name : 'npm install'
        uses : appleboy/ssh-action@master
        with :
          host : ${{ secrets.EC_HOST }}
          username : ${{ secrets.EC2_USER }}
          key : ${{ secrets.EC2_SSH_KEY }}          
          script : |
            cd /home/ubuntu/app
            npm install
            pm2 restart all || pm2 start app.js --name "awsexpress" --watch
